name: pytorch_example
channels:
  - defaults
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - pip:
    - torch==1.8.0
    - torchvision==0.9.0
    - mlflow>=1.0
    - tensorboardX
